### ISSUE TITLE
Refactor setup.py

### ISSUE THREAD

**Issue by kailashchoudhary11** [Sas2k/Lemon-CLI#6]
I think it would be better to fetch all the requirements from requirements.txt into install_requires list instead of hardcoding things.

**Comment by Sas2k** [comment]
That is a good Idea, Thanks for the Suggestion. Do you want to do it?, Or should I do it?

**Comment by kailashchoudhary11** [comment]
I want to do it!

**Comment by kailashchoudhary11** [comment]
May you assign it to me?

**Comment by Sas2k** [comment]
Sure. done go ahead and Do it.
