### ISSUE TITLE
Creating Example.py

### ISSUE THREAD

**Issue by kailashchoudhary11** [Sas2k/Lemon-CLI#8]
All the code mentioned in Readme file can be moved to a new python file so that the Readme file looks cleaner.

**Comment by Sas2k** [comment]
well, why not like the components python files in github
Like for the footer -> https://github.com/Sas2k/Lemon-CLI/blob/main/Lemon-CLI/components/Page/Footer.py
and so on.

**Comment by kailashchoudhary11** [comment]
So, should i add examples.py in components?

**Comment by Sas2k** [comment]
well, what I meant is directly link the component secion with the Readme
So instead of having
```markdown
### Footer
the page footer
<code>
```
this will be places
```markdown
### Footer

The page footer

[Footer](https://github.com/Sas2k/Lemon-CLI/blob/main/Lemon-CLI/components/Page/Footer.py)
```

**Comment by kailashchoudhary11** [comment]
Okkay Got It!

**Comment by Sas2k** [comment]
ok then, let me assign you, while your at it would you remove the Components directory in the Root Folder. I made it while testing forgot to remove it.

**Comment by kailashchoudhary11** [comment]
Okay Sure!

**Comment by Sas2k** [comment]
PR Merged, This issue is now closed
